language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^8.7
    - php: 7.3
      env: TYPO3_VERSION=^8.7
    - php: 7.4
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^9.5
    - php: 7.3
      env: TYPO3_VERSION=^9.5
    - php: 7.4
      env: TYPO3_VERSION=^9.5
    - php: 7.2
      env: TYPO3_VERSION=^10.3
    - php: 7.3
      env: TYPO3_VERSION=^10.3
    - php: 7.4
      env: TYPO3_VERSION=^10.3
    - php: 8.0
      env: TYPO3_VERSION=^11.5

sudo: false

before_script:
  - composer require typo3/minimal="$TYPO3_VERSION"

script:
  - vendor/bin/phpunit --color=always --coverage-clover=coverage.xml
  - vendor/bin/phpcs -n --standard=PSR2 --extensions=php tests/ src/

after_success:
    - bash <(curl -s https://codecov.io/bash)
